services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: homecooked-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: homecooked
      POSTGRES_USER: homecooked
      POSTGRES_PASSWORD: homecooked
